vich_uploader:
    db_driver: orm

    mappings:
        animal_picture:
            uri_prefix: /assets/images/animal_pictures
            upload_destination: "%kernel.project_dir%/public/assets/images/animal_pictures"



    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
