deployment:
  tasks:
    - rsync -av --progress . ~/api.etpa8594.odns.fr/ --exclude="src/Migrations/" --exclude="./env.dev" --exclude".cpanel.yml" --exclude=".git/"
    - cd ~/api.etpa8594.odns.fr/
    - composer update -n
    - APP_ENV=dev php bin/console make:migration -n
    - php bin/console d:m:m -n